apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-java-blue
    version: v1
  name: hello-java-blue-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-java-blue
  template:
    metadata:
      labels:
        app: hello-java-blue
        version: v2
    spec:
      containers:
      - image: chadmcrowell/hello-java-blue
        name: hello-java-blue