apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-java-green
    version: v2
  name: svc-java-green
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  selector:
    app: hello-java-green
    version: v2
  type: NodePort