apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-java-blue
    version: v1
  name: svc-java-blue
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
  selector:
    app: hello-java-blue
    version: v1
  type: NodePort