apiVersion: v1
kind: Pod
metadata:
  name: pod-emptyDir
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: main
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi