apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
spec:
  containers:
  - image: registry.k8s.io/test-webserver
    name: main
    volumeMounts:
    - mountPath: /scratch
      name: scratch-vol
  volumes:
  - name: scratch-vol
    hostPath:
      path: /data