apiVersion: v1
kind: Pod
metadata:
  labels:
    run: php-apache
  name: php-apache
spec:
  containers:
  - image: registry.k8s.io/hpa-example
    name: php-apache
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 200m