---
apiVersion: v1
kind: Pod
metadata:
  name: pod-emptydir
spec:
  containers:
  - image: busybox:1.28
    command:
    - sleep
    - "3600"
    name: main
    volumeMounts:
    - mountPath: /var/log
      name: logvol
  volumes:
  - name: logvol
    emptyDir:
      sizeLimit: 500Mi